name: Upload GitHub Repositories

on:
  push:
    branches:
      - develop

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Install Azure CLI
        run: sudo apt install az
      - name: Upload Repositories
        uses: azure/storage/blob@v1
        with:
          account: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
          container: ${{ secrets.AZURE_STORAGE_CONTAINER_NAME }}
          source: .
