name: Upload GitHub Repositories

on:
  push:
    branches:
      - develop

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Azure Login
        run: az login --use-device-code
      - name: Configure Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
#       - name: Install Azure CLI
#         run: sudo apt install azure-cli
      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      - name: Upload Repositories
        uses: actions/upload-artifact@v2
        with:
          name: repositories
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: upload
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Configure Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      - name: Download Repositories
        uses: actions/download-artifact@v2
        with:
          name: repositories
      - name: Upload Repositories to Azure Blob Storage
        uses: azure/storage-blob-upload@v1
        with:
          account-name: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
          account-key: ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}
          container-name: ${{ secrets.AZURE_STORAGE_CONTAINER_NAME }}
          source: .
      - run: echo "Upload complete"
