name: Upload GitHub Repositories

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  workflow_call:
  #Triggers the workflow on push or pull request events but only for the dev , stage and main branch
  push:
    branches:
      - develop
#     # Run the workflow on every push to the main branch
#   schedule:
#     - cron: "0 * * * *"
#     # Run the workflow every hour

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Debug - Print Azure Credentials
        run: echo "${{ secrets.AZURE_CREDENTIALS }}"
      - name: Verify Azure CLI installation
        run: az --version
      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      - name: Update Azure CLI
        run: az upgrade --yes
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_SERVICE_PRINCIPAL }}
          environment: azurecloud
          allow-no-subscriptions: false
          audience: api://AzureADTokenExchange
      - name: Debug - List Azure Subscriptions
        run: az account list
      - name: Upload Repositories
        uses: actions/upload-artifact@v2
        with:
          name: repositories
          path: .


#   deploy:
#     runs-on: ubuntu-latest
#     needs: upload
#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v2
#       - name: Configure Azure
#         uses: azure/login@v1
#         with:
#           creds: ${{ secrets.AZURE_CREDENTIALS }}
#       - name: Install Azure CLI
#         run: |
#           curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
#       - name: Download Repositories
#         uses: actions/download-artifact@v2
#         with:
#           name: repositories
#       - name: Upload Repositories to Azure Blob Storage
#         uses: azure/storage-blob-upload@v1
#         with:
#           account-name: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
#           account-key: ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}
#           container-name: ${{ secrets.AZURE_STORAGE_CONTAINER_NAME }}
#           source: .
#       - run: echo "Upload complete"
